const zenPhrases = [
  "Respira profondamente e lascia andare ciò che non puoi controllare.",
  "Il silenzio è una risposta quando la mente è calma.",
  "Ogni passo lento è comunque un passo avanti.",
  "La mente chiara nasce dall’accettazione.",
  "Non forzare il fiume: scorre già da solo.",
  "La pace arriva quando smetti di resistere.",
  "Sii presente: questo momento è tutto ciò che esiste.",
  "Lascia che i pensieri passino come nuvole.",
  "La semplicità è la forma più alta di saggezza.",
  "Non cercare fuori ciò che è già dentro.",
  "L’acqua non lotta, eppure supera ogni ostacolo.",
  "Accetta ciò che è, e trasforma ciò che puoi.",
  "Il vero riposo è una mente tranquilla.",
  "Cammina con calma, anche se il mondo corre.",
  "La pazienza è forza silenziosa.",
  "Ogni respiro è un nuovo inizio.",
  "Quando ascolti davvero, la risposta arriva.",
  "Non tutto va capito, alcune cose vanno sentite.",
  "La quiete interiore vale più di mille parole.",
  "Lascia spazio all’essere, non solo al fare.",
  "La chiarezza nasce quando smetti di giudicare.",
  "Ogni cosa arriva nel tempo giusto.",
  "La mente agitata vede problemi, quella calma vede soluzioni.",
  "Non trattenere ciò che vuole andare.",
  "Il presente non ha bisogno di essere migliorato.",
  "La pace non si cerca, si permette.",
  "Anche l’attesa fa parte del cammino.",
  "Sii gentile con te stesso come lo sei con gli altri.",
  "Il vuoto non è assenza, è spazio.",
  "La calma è una scelta consapevole.",
  "Osserva senza reagire.",
  "La lentezza rivela ciò che la fretta nasconde.",
  "Lascia che le cose siano come sono.",
  "Ogni momento è un maestro.",
  "La serenità nasce dall’equilibrio.",
  "Non inseguire, attrai con la quiete.",
  "La mente stabile vede lontano.",
  "La pace inizia da una scelta interna.",
  "Accogli il cambiamento senza paura.",
  "Il silenzio chiarisce ciò che il rumore confonde.",
  "Non tutto richiede una risposta.",
  "Sii acqua, non pietra.",
  "Il respiro riporta sempre al centro.",
  "Rallenta, sei già arrivato.",
  "La calma è potere invisibile.",
  "Lascia andare per fare spazio.",
  "Ogni giorno è pratica.",
  "La quiete non dipende da ciò che accade.",
  "Essere è già abbastanza."
];

const randomPhrase = arr => arr[Math.floor(Math.random() * arr.length)];